language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI: false
  notifications:  
  email:  
    recipients:  
      - jennytlam18@gmail.com  
      on_success: always  
      on_failure: always
script:
  - npm test
  - npm run build
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
