language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI: false
script:
  - npm test
  - npm run build
notifications:
  email:
    - jenny.t.lam18@gmail.com
    - jennylam2021@u.northwestern.edu
