language: node_js
node_js:
  - "stable"
env:
  - CI: false
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
notifications:
  email:
    recipients:
      - jennytlam18@gmail.com
      - jennylam2021@u.northwestern.edu
    on_success: always
    on_failure: always
    
