notifications:  
  email:  
    recipients:  
      - jennytlam18@gmail.com  
      on_success: always  
      on_failure: always
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI: false
script:
  - npm test
  - npm run build

